# Generated by Django 4.2.1 on 2023-06-20 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(K)([ABCDEFGHJKLMNPQRSTUVWXYZ]){2}( ){1}(\\d){3}([ABCDEFGHJKLMNPQRSTUVWXYZ])$', message='Invalid Number Plate')])),
                ('image', models.ImageField(upload_to='static/car_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_no', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(0)([127])(\\d){8}$', message='Invalid phone numbers')])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
