# Generated by Django 4.2.1 on 2023-06-23 09:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Owner', '0004_alter_car_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 23), 'Start date can not be less than today')])),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 23), 'Start date can not be less than today')])),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
