# Generated by Django 4.2.1 on 2023-06-23 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='from_destination',
            field=models.CharField(max_length=20, null='True', validators=[django.core.validators.RegexValidator("^([a-zA-Z])[a-zA-Z'\\d ]+$", message='Must be a valid name of a place')]),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='hire',
            name='phone_no',
            field=models.CharField(max_length=20, null='True', unique=True, validators=[django.core.validators.RegexValidator('^(0)([127])(\\d){8}$', message='Invalid phone numbers')]),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='hire',
            name='to_destination',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator("^([a-zA-Z])[a-zA-Z'\\d ]+$", message='Must be a valid name of a place')]),
        ),
    ]
