# Generated by Django 4.2.1 on 2023-06-23 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hire', '0002_hire_from_destination_hire_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='phone_no',
            field=models.CharField(max_length=20, null='True', validators=[django.core.validators.RegexValidator('^(0)([127])(\\d){8}$', message='Invalid phone numbers')]),
        ),
    ]
