# Generated by Django 4.2.1 on 2023-07-05 14:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hire', '0003_alter_hire_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 5), 'End date can not be less than today')]),
        ),
        migrations.AlterField(
            model_name='hire',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 5), 'Start date can not be less than today')]),
        ),
    ]
